# NBA ROLE PLAYER KNN ANALYSIS

### IMPORTING DATA & LIBRARIES

In [ ]:
# nba data
from nba_api.stats.endpoints import playercareerstats
from nba_api.stats.static import teams
from nba_api.stats.static import players

# packages
import pandas as pd
import altair as alt
import matplotlib.pyplot as plt
import seaborn as sn

In [10]:
# load nba team information
nba_teams = teams.get_teams()

In [11]:
# load nba player info
nba_players = players.get_players()

In [15]:
# load in chunk data from google sheets 9from URL)
nba_data = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQ-1fqyvskEHodIPX8O-4_QvUHmXUXCAvNETbYZs8e0ZRO_trGzV64tDjskf_oe_t83JjpzOS_D5kfZ/pub?gid=1833496207&single=true&output=csv")
nba_data

,Unnamed: 0,name,player_height,player_weight,college,country,draft_year,draft_round,draft_number,pts,...,FG% by Distance 16-3P,FG% by Distance 3P,% of FG Ast'd 2P,% of FG Ast'd 3P,Dunks %FGA,# of Dunks,Corner 3s %3PA,Corner 3s 3P%,Attempted Heaves,# of Heaves
0,0,Jamal Crawford,195.58,90.718400,Michigan,USA,2000,1,8,4.6,...,0.363,0.350,0.439,0.951,0.013,3.0,0.068,0.500,1.0,0.0
1,1,Jamal Mashburn,203.20,109.315672,Kentucky,USA,1993,1,4,20.1,...,0.332,0.356,0.534,0.893,0.016,19.0,0.260,0.413,1.0,0.0
2,2,Ira Bowman,195.58,88.450440,Pennsylvania,USA,Undrafted,Undrafted,Undrafted,0.0,...,NaN,NaN,NaN,NaN,0.000,0.0,NaN,NaN,0.0,0.0
3,3,Jamel Thomas,198.12,99.336648,Providence,USA,Undrafted,Undrafted,Undrafted,2.6,...,0.000,0.333,0.200,1.000,0.000,0.0,0.333,1.000,0.0,0.0
4,4,Dikembe Mutombo,218.44,120.201880,Georgetown,Congo,1991,1,4,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9751,9751,Markieff Morris,205.74,111.130040,Kansas,USA,2011,1,13,7.6,...,0.538,0.333,0.512,1.000,0.044,4.0,0.487,0.368,0.0,0.0
9752,9752,Markelle Fultz,193.04,94.800728,Washington,USA,2017,1,1,10.8,...,0.370,0.235,0.177,0.500,0.011,2.0,0.118,0.500,3.0,0.0
9753,9753,Marcus Smart,193.04,99.790240,Oklahoma State,USA,2014,1,6,12.1,...,0.105,0.331,0.365,0.916,0.013,8.0,0.233,0.345,2.0,0.0
9754,9754,Marcus Garrett,195.58,92.986360,Kansas,USA,Undrafted,Undrafted,Undrafted,1.1,...,0.500,0.250,0.500,1.000,0.000,0.0,0.500,0.000,0.0,0.0
9755,9755,Micah Potter,208.28,112.490816,Wisconsin,USA,Undrafted,Undrafted,Undrafted,4.0,...,NaN,0.000,0.600,NaN,0.000,0.0,0.000,NaN,0.0,0.0

### EDA

In [16]:
## Removing 'Unnamed: 0' column along with duplicate columns
nba_data = nba_data.drop(columns = ["Unnamed: 0", "pts", "reb", "ast"])

In [17]:
## keep NAs where NA is placeholder for a zero - example: some NAs are because a center didn't take 3 pointers
pd.DataFrame(data.isna().sum()).sort_values(by = 0,ascending = False).head(20)

# Removing all other rows with NA values
data = data.dropna()
data.isna().values.any()

                               0
% of FG Ast'd 3P            2687
Corner 3s 3P%               2586
FG% by Distance 3P          1488
Corner 3s %3PA              1488
FG% by Distance 16-3P        906
FG% by Distance 10-16        868
FG% by Distance 3-10         651
FG% by Distance 0-3          493
% of FG Ast'd 2P             446
FG% by Distance 2P           327
% of FGA by Distance 3-10    293
Dunks %FGA                   293
% of FGA by Distance 2P      293
Dist.                        293
FG%                          293
% of FGA by Distance 0-3     293
% of FGA by Distance 3P      293
% of FGA by Distance 16-3P   293
% of FGA by Distance 10-16   293
# of Heaves                  253